# backend/scripts/species_data.py

MOCK_SPECIES = [
    {
        "species_id": "red-panda",
        "name": "Red Panda",
        "location": "China",
        "clues": [
            "I am a small, rust-colored mammal with a ringed tail.",
            "I have a 'false thumb' to help me grip stalks.",
            "I am not a bear, but I share my diet of bamboo with the Giant Panda.",
            "My misty, high-altitude forest home is nestled in the eastern Himalayas.",
            "To find me, you must look in the southwestern provinces of China.",
        ],
        "conservation_info": "Endangered (Population: < 10,000). They are threatened by habitat fragmentation from commercial logging and agriculture. To help, organizations are establishing protected forest corridors and working with local communities to reduce reliance on forest resources.",
    },
    {
        "species_id": "snow-leopard",
        "name": "Snow Leopard",
        "location": "Mongolia",
        "clues": [
            "My smoky-gray coat is covered in dark rosettes for camouflage.",
            "My exceptionally large paws act as natural snowshoes.",
            "I am known as the 'Ghost of the Mountains' because I am rarely seen.",
            "I leap across ravines in the harsh, rugged Altai Mountains.",
            "My largest stronghold is the cold, nomadic steppes of Mongolia.",
        ],
        "conservation_info": "Vulnerable (Population: 4,000 - 6,500). They are threatened by retaliatory killings by herders protecting livestock and habitat loss due to climate change. To help, conservationists provide livestock insurance to herders and build predator-proof corrals.",
    },
    {
        "species_id": "galapagos-penguin",
        "name": "Galapagos Penguin",
        "location": "Ecuador",
        "clues": [
            "I am the second smallest species of my kind in the world.",
            "I do not live in an icy, polar environment.",
            "I nest in caves and crevices made of volcanic rock.",
            "I rely on the cold Cromwell Current flowing into South America.",
            "I live on a famous archipelago owned by the country of Ecuador.",
        ],
        "conservation_info": "Endangered (Population: < 2,000). They are severely affected by El Niño events warming the ocean and disrupting their marine food web, leading to starvation. To help, organizations are creating strict marine protected areas and building artificial nesting sites.",
    },
    {
        "species_id": "sumatran-orangutan",
        "name": "Sumatran Orangutan",
        "location": "Indonesia",
        "clues": [
            "I am a great ape with striking reddish-orange hair.",
            "Mature males of my species develop wide, fleshy cheek pads.",
            "I am almost exclusively arboreal, rarely coming down from the canopy.",
            "My name translates to 'person of the forest' in the local language.",
            "I am found exclusively on one massive island in the nation of Indonesia.",
        ],
        "conservation_info": "Critically Endangered (Population: ~14,000). They face massive population drops driven by illegal logging and widespread deforestation for palm oil plantations. To help, consumers can look for certified sustainable palm oil products, while groups are actively rescuing isolated apes and reforesting.",
    },
    {
        "species_id": "axolotl",
        "name": "Axolotl",
        "location": "Mexico",
        "clues": [
            "I can regenerate limbs, spinal cords, and even my heart.",
            "I exhibit neoteny, meaning I never undergo metamorphosis.",
            "I breathe through large, feathery external gills.",
            "My wild population is nearly extinct due to heavy urbanization.",
            "I am natively found only in the lake complex of Xochimilco, Mexico.",
        ],
        "conservation_info": "Critically Endangered (Population: < 1,000 in the wild). They are affected by severe water pollution from nearby cities and the introduction of invasive predatory fish like tilapia. To help, scientists are working with local farmers to create traditional, pesticide-free floating gardens to clean the lake water.",
    },
    {
        "species_id": "amur-leopard",
        "name": "Amur Leopard",
        "location": "Russia",
        "clues": [
            "I am a solitary nocturnal predator capable of running 37 mph.",
            "My coat changes from reddish-yellow in summer to light, thick fur in winter.",
            "I am adapted to a freezing climate, unlike my relatives in Africa.",
            "Fewer than 100 of us are left in the snowy temperate forests.",
            "My last remaining wild refuge is the Primorsky Krai region of eastern Russia.",
        ],
        "conservation_info": "Critically Endangered (Population: ~100). They are threatened by poaching for their beautiful fur and habitat loss from illegal logging and forest fires. To help, governments are enforcing strict anti-poaching laws and have established a massive transboundary national park.",
    },
    {
        "species_id": "vaquita",
        "name": "Vaquita",
        "location": "Mexico",
        "clues": [
            "I am the world's smallest marine mammal.",
            "I have dark rings around my eyes and dark patches on my lips.",
            "I am frequently caught and drowned as bycatch in illegal gillnets.",
            "Fewer than 20 of us remain in the wild today.",
            "I am found absolutely nowhere else but the northern Gulf of California, Mexico.",
        ],
        "conservation_info": "Critically Endangered (Population: < 20). They are drowning as bycatch in illegal gillnets set by poachers trying to catch the totoaba fish. To help, naval patrols are actively removing illegal nets from the water, and researchers are monitoring the remaining individuals acoustically.",
    },
    {
        "species_id": "javan-rhino",
        "name": "Javan Rhino",
        "location": "Indonesia",
        "clues": [
            "I have dusky grey skin that looks like heavy armor plating.",
            "Unlike my African cousins, I only have a single horn.",
            "I am the rarest of the five species in my family.",
            "My entire global population is restricted to a single national park.",
            "I live exclusively in Ujung Kulon National Park in Indonesia.",
        ],
        "conservation_info": "Critically Endangered (Population: ~75). They are extremely vulnerable to natural disasters (tsunamis) and disease due to existing in only one small location. To help, conservationists are eradicating invasive palm species to let rhino food plants grow, and scouting secondary locations to establish a new herd.",
    },
    {
        "species_id": "mountain-gorilla",
        "name": "Mountain Gorilla",
        "location": "Rwanda",
        "clues": [
            "I have thicker and longer hair than other apes to survive cold temperatures.",
            "I live in complex social groups led by a dominant silverback.",
            "I build a new nest on the ground every single night to sleep.",
            "I am found high in the volcanic slopes of the Virunga Massif.",
            "You must trek into the misty mountains of Rwanda to see me.",
        ],
        "conservation_info": "Endangered (Population: ~1,000). They are affected by poaching, habitat loss from human encroachment, and susceptibility to human diseases. To help, closely monitored eco-tourism provides funding for intensive veterinary care and community development around the parks.",
    },
    {
        "species_id": "hawksbill-turtle",
        "name": "Hawksbill Turtle",
        "location": "Australia",
        "clues": [
            "I am a highly migratory marine reptile.",
            "I am named for my narrow, pointed beak.",
            "My diet consists almost exclusively of toxic sea sponges.",
            "My colorful, overlapping carapace scales make me a target for poachers.",
            "I am vital to maintaining the health of the Great Barrier Reef in Australia.",
        ],
        "conservation_info": "Critically Endangered (Population: Decreasing). The illegal wildlife trade heavily targets them for their 'tortoiseshell' to make jewelry and trinkets. To help, global efforts include international trade bans, protecting nesting beaches from development, and reducing artificial light pollution.",
    },
    {
        "species_id": "saola",
        "name": "Saola",
        "location": "Vietnam",
        "clues": [
            "I am so elusive I was only discovered by scientists in 1992.",
            "I possess striking white markings on my face.",
            "I have two long, straight, parallel horns.",
            "I am affectionately known by conservationists as the 'Asian Unicorn'.",
            "I am found only in the dense Annamite Mountains of Vietnam.",
        ],
        "conservation_info": "Critically Endangered (Population: Unknown). They are threatened by indiscriminate hunting using wire snare traps set for other animals like wild boar. To help, local ranger patrols are systematically combing the forests to dismantle millions of illegal snares.",
    },
    {
        "species_id": "kakapo",
        "name": "Kakapo",
        "location": "New Zealand",
        "clues": [
            "I am the heaviest parrot in the world.",
            "I am completely nocturnal and completely flightless.",
            "I freeze like a statue when threatened rather than running away.",
            "I only breed when native Rimu trees drop massive amounts of fruit.",
            "I am an endemic bird heavily protected on offshore islands of New Zealand.",
        ],
        "conservation_info": "Critically Endangered (Population: ~250). They have been decimated by introduced mammalian predators like stoats, rats, and feral cats. To help, all remaining individuals have been moved to predator-free islands where they are intensely monitored and fed during breeding seasons.",
    },
    {
        "species_id": "california-condor",
        "name": "California Condor",
        "location": "United States",
        "clues": [
            "I am the largest land bird in North America.",
            "My bald head can flush pink or red depending on my mood.",
            "I am a massive scavenger that feeds exclusively on carrion.",
            "In 1987, my entire wild population was captured to save us from extinction.",
            "I soar over the Grand Canyon and the western coast of the United States.",
        ],
        "conservation_info": "Critically Endangered (Population: ~350 in the wild). They suffer from lead poisoning from ingesting spent ammunition fragments left in animal carcasses. To help, there are legislative pushes to ban lead ammunition, combined with rigorous captive breeding and release programs.",
    },
    {
        "species_id": "iberian-lynx",
        "name": "Iberian Lynx",
        "location": "Spain",
        "clues": [
            "I have characteristic tufted ears and a short, bobbed tail.",
            "I have a distinct 'beard' of hair around my face.",
            "My diet is almost 90% rabbits.",
            "A disease wiping out my prey nearly caused my extinction.",
            "I am found only in the Mediterranean forests of southern Spain.",
        ],
        "conservation_info": "Endangered (Population: ~1,000). They are threatened by a heavy reliance on rabbit populations, which crashed due to diseases like myxomatosis, as well as vehicle strikes. To help, conservationists are reintroducing healthy rabbits to their habitats and building safe wildlife underpasses beneath busy roads.",
    },
    {
        "species_id": "tasmanian-devil",
        "name": "Tasmanian Devil",
        "location": "Australia",
        "clues": [
            "I am the world's largest surviving carnivorous marsupial.",
            "I store fat in my tail, so a plump tail means I am healthy.",
            "I emit loud, disturbing screeches when competing for food.",
            "A contagious facial tumor disease has decimated my wild population.",
            "I live exclusively on an island state belonging to Australia.",
        ],
        "conservation_info": "Endangered (Population: Decreasing). They are decimated by Devil Facial Tumor Disease (DFTD), an aggressive transmissible cancer spread through biting. To help, scientists are establishing completely isolated, disease-free 'insurance populations' on the mainland and offshore islands.",
    },
    {
        "species_id": "philippine-eagle",
        "name": "Philippine Eagle",
        "location": "Philippines",
        "clues": [
            "I am one of the largest and most powerful birds of prey.",
            "I have a shaggy crest of feathers that resembles a lion's mane.",
            "I am an apex predator that sometimes hunts macaques.",
            "I require vast tracts of old-growth tropical rainforest to hunt.",
            "I am the official national bird of the Philippines.",
        ],
        "conservation_info": "Critically Endangered (Population: ~400 pairs). They face rapid deforestation from logging and agriculture, and being shot by locals out of fear or for sport. To help, groups are working directly with indigenous communities to manage and protect forest resources, alongside strict anti-shooting laws.",
    },
    {
        "species_id": "giant-otter",
        "name": "Giant Otter",
        "location": "Brazil",
        "clues": [
            "I can grow up to 6 feet long.",
            "I have a distinct, pale throat patch unique to each individual.",
            "I am highly social and live in noisy, aggressive family groups.",
            "I am known locally as the 'river wolf'.",
            "I thrive in the slow-moving rivers of the Pantanal and Amazon basin in Brazil.",
        ],
        "conservation_info": "Endangered (Population: ~4,000). They are affected by habitat degradation, overfishing of their prey, and mercury pollution from illegal gold mining. To help, authorities are enforcing protection of critical river systems and prosecuting illegal mining operations.",
    },
    {
        "species_id": "bluefin-tuna",
        "name": "Bluefin Tuna",
        "location": "Japan",
        "clues": [
            "I am built for speed, shaped like a massive metallic torpedo.",
            "I am warm-blooded, allowing me to dive into freezing ocean depths.",
            "I can weigh over 1,000 pounds.",
            "I am highly prized and heavily overfished for the global sushi market.",
            "The largest fish market for my meat is located in Tokyo, Japan.",
        ],
        "conservation_info": "Endangered (Population: Decreasing). They suffer from massive commercial overfishing driven by extreme high-value demand in international markets. To help, organizations are implementing strict international fishing quotas and advancing tracking technologies to stop illegal fishing vessels.",
    },
    {
        "species_id": "african-wild-dog",
        "name": "African Wild Dog",
        "location": "Botswana",
        "clues": [
            "I have large, rounded, Mickey Mouse-like ears.",
            "I have a mottled, 'painted' coat pattern unique to me.",
            "My pack has an incredibly high hunting success rate on the savanna.",
            "My pack votes on whether to initiate a hunt by sneezing.",
            "My largest remaining populations roam the Okavango Delta in Botswana.",
        ],
        "conservation_info": "Endangered (Population: ~6,000). They are threatened by habitat fragmentation limiting their massive hunting ranges, and fatal diseases like rabies caught from domestic dogs. To help, conservationists are vaccinating domestic dogs on the borders of national parks and securing connected wildlife corridors.",
    },
    {
        "species_id": "red-wolf",
        "name": "Red Wolf",
        "location": "United States",
        "clues": [
            "I am smaller than a gray wolf but larger than a coyote.",
            "I have a reddish tinge on my head, ears, and legs.",
            "I often mate for life and live in tight-knit family packs.",
            "I was declared extinct in the wild in 1980 before being carefully reintroduced.",
            "My only wild population exists on a small coastal peninsula in the United States.",
        ],
        "conservation_info": "Critically Endangered (Population: ~20 in the wild). They are affected by genetic hybridization with coyotes, vehicle strikes, and gunshot mortality. To help, efforts include captive breeding programs, collaring wolves for tracking, and sterilizing local coyotes to prevent interbreeding.",
    },
    {
        "species_id": "okapi",
        "name": "Okapi",
        "location": "Democratic Republic of the Congo",
        "clues": [
            "I secrete a velvety, waterproofing oil from my dark coat.",
            "I have zebra-like stripes on my legs and hindquarters.",
            "My tongue is so long I can wash my own eyelids.",
            "Despite my appearance, my closest living relative is the giraffe.",
            "I live exclusively in the dense Ituri rainforest of the Democratic Republic of the Congo.",
        ],
        "conservation_info": "Endangered (Population: ~15,000). They are threatened by deforestation from slash-and-burn agriculture, illegal mining, and poaching for bushmeat. To help, organizations are funding highly trained park rangers to dismantle illegal mining camps and remove snares in wildlife reserves.",
    },
    {
        "species_id": "numbat",
        "name": "Numbat",
        "location": "Australia",
        "clues": [
            "I am a small marsupial, but I do not have a pouch.",
            "I have striking white stripes across my reddish-brown back.",
            "My diet consists entirely of up to 20,000 termites a day.",
            "I am active only during the day, unlike most of my relatives.",
            "I am the faunal emblem of Western Australia.",
        ],
        "conservation_info": "Endangered (Population: < 1,000). They were almost entirely wiped out by introduced predators, specifically red foxes and feral cats. To help, wildlife agencies are running intensive predator baiting programs and relocating individuals to fenced, predator-free sanctuaries.",
    },
    {
        "species_id": "aye-aye",
        "name": "Aye-Aye",
        "location": "Madagascar",
        "clues": [
            "I am the world's largest nocturnal primate.",
            "I have rodent-like teeth that never stop growing.",
            "Many locals consider me a bad omen and kill me on sight.",
            "I tap on trees and use an elongated middle finger to pull out grubs.",
            "I am endemic to the isolated island nation of Madagascar.",
        ],
        "conservation_info": "Endangered (Population: Decreasing). They face deforestation destroying their tree-canopy habitats, and being killed due to deeply rooted local superstitions. To help, organizations run local education programs to dispel myths, and establish protected reserves where logging is prohibited.",
    },
    {
        "species_id": "golden-lion-tamarin",
        "name": "Golden Lion Tamarin",
        "location": "Brazil",
        "clues": [
            "I am a tiny monkey weighing less than two pounds.",
            "My bright orange coat makes me highly visible in the canopy.",
            "I live in small family groups that sleep in tree cavities.",
            "I get my name from the impressive mane of hair around my face.",
            "I am found only in the fragmented Atlantic coastal forests of Brazil.",
        ],
        "conservation_info": "Endangered (Population: ~2,500). Urban expansion has severely fragmented their coastal forest habitat, preventing genetic diversity. To help, conservationists are planting trees to create crucial forest corridors that connect isolated family groups.",
    },
    {
        "species_id": "quokka",
        "name": "Quokka",
        "location": "Australia",
        "clues": [
            "I am a small macropod, closely related to wallabies.",
            "I have no natural fear of humans.",
            "I can survive for long periods without drinking water.",
            "I am famous across the internet for my seemingly permanent 'smile'.",
            "My largest remaining population is heavily protected on Rottnest Island in Australia.",
        ],
        "conservation_info": "Vulnerable (Population: ~10,000). Mainland populations were decimated by invasive foxes and cats, restricting them heavily to islands. To help, there are strict rules against human feeding on the islands and invasive species control on the mainland.",
    },
    {
        "species_id": "shoebill",
        "name": "Shoebill",
        "location": "Uganda",
        "clues": [
            "I am a massive, prehistoric-looking bird.",
            "I can stand completely motionless for hours while hunting.",
            "My favorite prey includes lungfish and baby crocodiles.",
            "My beak is huge, bulbous, and resembles a wooden clog.",
            "I inhabit the massive freshwater swamps of East Africa, primarily in Uganda.",
        ],
        "conservation_info": "Vulnerable (Population: ~5,000). They are threatened by the drainage of their swamp habitats for agriculture, cattle grazing, and pollution from oil exploration. To help, key wetlands are being designated as internationally protected Ramsar sites to halt drainage.",
    },
    {
        "species_id": "komodo-dragon",
        "name": "Komodo Dragon",
        "location": "Indonesia",
        "clues": [
            "I am the heaviest lizard on Earth.",
            "I use my forked tongue to taste the air for carrion miles away.",
            "I have venom glands that induce shock and blood loss in my prey.",
            "I am capable of reproducing through parthenogenesis (without a mate).",
            "I am an apex predator isolated to a few lesser Sunda islands in Indonesia.",
        ],
        "conservation_info": "Endangered (Population: ~3,000). Rising sea levels from climate change threaten to swallow their highly restricted island habitats. To help, their islands are protected entirely within a National Park and tourism impact is strictly managed.",
    },
    {
        "species_id": "marine-iguana",
        "name": "Marine Iguana",
        "location": "Ecuador",
        "clues": [
            "I have a dark body that absorbs sunlight to warm me up.",
            "I sneeze out excess salt from special glands in my nose.",
            "My blunt snout allows me to scrape algae off underwater rocks.",
            "I am the only lizard in the world that forages in the ocean.",
            "I am endemic to the Galapagos archipelago, governed by Ecuador.",
        ],
        "conservation_info": "Vulnerable (Population: ~250,000). They are affected by the increased frequency of El Niño events which kill off the marine algae they depend on. To help, conservationists are eradicating invasive predators like rats and cats from the islands to protect their eggs.",
    },
    {
        "species_id": "hellbender",
        "name": "Hellbender",
        "location": "United States",
        "clues": [
            "I am the largest aquatic salamander in North America.",
            "I have loose, wrinkly skin that helps me absorb oxygen from the water.",
            "I require cold, fast-moving, highly oxygenated streams.",
            "I am affectionately called the 'snot otter' or 'lasagna lizard'.",
            "I hide under large, flat rocks in the Appalachian rivers of the United States.",
        ],
        "conservation_info": "Endangered locally (Population: Decreasing). Agricultural runoff and deforestation cause sedimentation, which fills in the rocky crevices they use for shelter. To help, groups are restoring riparian buffers (planting trees along riverbanks) to stop soil erosion and filter out pollutants.",
    },
    {
        "species_id": "sun-bear",
        "name": "Sun Bear",
        "location": "Malaysia",
        "clues": [
            "I am the smallest bear species in the world.",
            "I am highly arboreal and frequently sleep in trees.",
            "I have an exceptionally long tongue used for extracting honey.",
            "I have a distinct U-shaped golden patch on my chest.",
            "I inhabit the dense tropical rainforests of Southeast Asia, particularly Malaysia.",
        ],
        "conservation_info": "Vulnerable (Population: Decreasing). They face rampant deforestation for palm oil and capture for the illegal bear bile trade. To help, organizations are rescuing bears from illegal captivity and advocating for the global boycott of bear bile products.",
    },
    {
        "species_id": "maned-wolf",
        "name": "Maned Wolf",
        "location": "Brazil",
        "clues": [
            "I am an omnivore, eating mostly lobeira fruit and small rodents.",
            "My urine has a strong odor often compared to marijuana.",
            "I look like a large red fox walking on black stilts.",
            "My incredibly long legs help me see above tall savanna grasses.",
            "I roam the vast Cerrado biomes of South America, primarily in Brazil.",
        ],
        "conservation_info": "Near Threatened (Population: ~17,000). They are threatened by the rapid conversion of the Cerrado savanna into massive agricultural farmland, causing habitat loss and vehicle strikes. To help, conservationists are working with farmers to implement sustainable agriculture and protecting large tracts of the Cerrado.",
    },
    {
        "species_id": "pygmy-hippo",
        "name": "Pygmy Hippo",
        "location": "Liberia",
        "clues": [
            "I am much smaller and less aquatic than my famous, massive cousin.",
            "I am primarily nocturnal and highly solitary.",
            "I secrete a pink fluid that acts as sunscreen and an antibiotic.",
            "I seek refuge in muddy forest streams and swamps.",
            "I am endemic to the dense upper Guinean forests of West Africa, primarily Liberia.",
        ],
        "conservation_info": "Endangered (Population: ~2,000). They are affected by unregulated logging operations fragmenting their forest homes, and opportunistic hunting for bushmeat. To help, scientists are surveying isolated populations with camera traps to establish newly protected forest reserves.",
    },
    {
        "species_id": "dugong",
        "name": "Dugong",
        "location": "Australia",
        "clues": [
            "I am a large marine mammal closely related to elephants.",
            "Unlike manatees, I have a fluked tail similar to a dolphin's.",
            "My heavy bones act as ballast to keep me grazing on the sea floor.",
            "My diet consists almost entirely of coastal seagrass.",
            "My largest remaining population is found in the coastal waters of Australia.",
        ],
        "conservation_info": "Vulnerable (Population: Decreasing). They are threatened by coastal development, agricultural runoff, and dredging which completely destroy the seagrass meadows they eat. To help, authorities are using marine spatial planning to restrict dredging and establishing boat-strike speed limits in critical bays.",
    },
    {
        "species_id": "narwhal",
        "name": "Narwhal",
        "location": "Canada",
        "clues": [
            "I lack a dorsal fin, allowing me to swim easily under thick ice.",
            "I can dive up to a mile deep to hunt for bottom-dwelling halibut.",
            "I communicate using a complex series of clicks and whistles.",
            "Males of my species possess a spiraled tusk that is actually a massive tooth.",
            "I am uniquely adapted to the freezing Arctic waters of northern Canada.",
        ],
        "conservation_info": "Near Threatened (Population: ~100,000). Climate change is rapidly melting Arctic sea ice, which increases disruptive commercial shipping traffic and oil exploration in their habitats. To help, groups are lobbying to reroute major shipping lanes away from their critical summer feeding grounds.",
    },
    {
        "species_id": "fossa",
        "name": "Fossa",
        "location": "Madagascar",
        "clues": [
            "I look like a strange mix between a cat, a dog, and a mongoose.",
            "My semi-retractable claws and long tail make me an expert climber.",
            "I am the largest mammalian carnivore in my ecosystem.",
            "My absolute favorite prey to hunt in the trees are lemurs.",
            "I rule the forests of my isolated, endemic island nation of Madagascar.",
        ],
        "conservation_info": "Vulnerable (Population: ~2,500). They are threatened by rampant slash-and-burn agriculture decimating the forests they rely on to hunt. To help, Madagascar is expanding national parks and working with local communities to develop sustainable farming alternatives.",
    },
    {
        "species_id": "binturong",
        "name": "Binturong",
        "location": "India",
        "clues": [
            "I am a keystone species because I help spread fig seeds.",
            "I am one of only two carnivores with a fully prehensile tail.",
            "I live high in the thick canopy of tropical forests.",
            "My scent glands produce a smell exactly like hot buttered popcorn.",
            "I am often called a 'bearcat' and can be found in the northeastern forests of India.",
        ],
        "conservation_info": "Vulnerable (Population: Decreasing). They are captured for the illegal exotic pet trade and hunted for their meat in local bushmeat markets. To help, authorities are enforcing stricter anti-poaching laws and monitoring online illegal wildlife marketplaces.",
    },
    {
        "species_id": "sloth-bear",
        "name": "Sloth Bear",
        "location": "India",
        "clues": [
            "I carry my young cubs on my back while I forage.",
            "I have shaggy black fur and a prominent white Y-shaped chest mark.",
            "I lack upper incisors, creating a gap that helps me suck up insects.",
            "I use my long lower lip like a vacuum to eat my favorite food: termites.",
            "I inhabit the dry and moist forests of the Indian subcontinent.",
        ],
        "conservation_info": "Vulnerable (Population: ~20,000). They suffer from extreme human-wildlife conflict resulting in retaliatory killings when bears wander into villages or farms. To help, conservationists are providing financial compensation to farmers for crop damage to prevent revenge killings of the bears.",
    },
    {
        "species_id": "tapir",
        "name": "Tapir",
        "location": "Brazil",
        "clues": [
            "I am an excellent swimmer and use river water to escape predators.",
            "My calves are born with watermelon-like stripes and spots for camouflage.",
            "I am considered a living fossil, largely unchanged for millions of years.",
            "I have a short, prehensile snout used to grab leaves and branches.",
            "I am a large, pig-like herbivore found in the Neotropical forests of Brazil.",
        ],
        "conservation_info": "Vulnerable (Population: Decreasing). They are highly vulnerable to deforestation from cattle ranching and hunting, which is devastating due to their very slow reproduction rate. To help, organizations are promoting sustainable forestry practices and researching their crucial role as seed dispersers.",
    },
    {
        "species_id": "gharial",
        "name": "Gharial",
        "location": "India",
        "clues": [
            "My legs are too weak to lift my heavy belly off the ground.",
            "Adult males grow a distinct bulbous growth on the tip of their snout.",
            "I am a crocodilian, but my diet consists exclusively of fish.",
            "My exceptionally long, thin snout is perfectly adapted for swiping through water.",
            "I live only in the clear, fast-flowing freshwater rivers of northern India.",
        ],
        "conservation_info": "Critically Endangered (Population: ~600). River damming altering water flow, and illegal sand mining destroy the sandbanks where they nest. To help, conservationists are collecting wild eggs, incubating them safely in captivity, and releasing juveniles back into protected rivers.",
    },
    {
        "species_id": "pangolin",
        "name": "Pangolin",
        "location": "China",
        "clues": [
            "I walk awkwardly on my hind legs, using my heavy tail for balance.",
            "I lack teeth, using a sticky tongue longer than my body to eat ants.",
            "I roll into a tight, impenetrable ball when threatened.",
            "I am the only mammal in the world completely covered in keratin scales.",
            "I am heavily poached for traditional medicine markets, particularly in China.",
        ],
        "conservation_info": "Critically Endangered (Population: Declining rapidly). They are the most illegally trafficked wild mammal on the planet, hunted entirely for their scales and meat. To help, international trade bans are being implemented and sniffer dogs are utilized at borders to intercept traffickers.",
    },
    {
        "species_id": "asian-elephant",
        "name": "Asian Elephant",
        "location": "India",
        "clues": [
            "I maintain tight, matriarchal social herds.",
            "I have a single 'finger' at the end of my trunk.",
            "Only the males of my species grow visible tusks.",
            "I have smaller, more rounded ears than my African counterpart.",
            "I hold immense cultural and religious significance in the jungles of India.",
        ],
        "conservation_info": "Endangered (Population: ~40,000). Extreme habitat loss forces elephants into human settlements, leading to deadly human-wildlife conflict over destroyed crops. To help, conservationists are installing early-warning systems for villages and planting chili-pepper fences, which naturally deter elephants.",
    },
    {
        "species_id": "green-turtle",
        "name": "Green Turtle",
        "location": "Australia",
        "clues": [
            "I am a large, hard-shelled marine reptile.",
            "I am named not for the color of my shell, but for the color of my body fat.",
            "I rely heavily on shallow seagrass beds for food.",
            "I migrate thousands of miles to nest on the exact beach where I was born.",
            "One of my most important nesting grounds is the Great Barrier Reef in Australia.",
        ],
        "conservation_info": "Endangered (Population: Decreasing). They are threatened by accidental capture in commercial fishing gear (bycatch) and the rampant spread of oceanic plastic pollution. To help, it is mandated to use Turtle Excluder Devices (TEDs) on fishing nets to allow them to escape if caught.",
    },
    {
        "species_id": "whooping-crane",
        "name": "Whooping Crane",
        "location": "United States",
        "clues": [
            "I have snow-white plumage with a striking crimson crown.",
            "My distinct, loud call can be heard for miles across the marsh.",
            "In 1941, my global population dropped to just 15 individuals.",
            "I am the tallest bird in North America.",
            "I undertake a massive migration to winter in the coastal wetlands of the United States.",
        ],
        "conservation_info": "Endangered (Population: ~800). They suffer from the loss of critical wetland stopover habitats along their massive migration route due to agriculture and development. To help, there are intense captive breeding programs using ultralight aircraft to teach human-raised chicks their migration routes.",
    },
    {
        "species_id": "black-rhino",
        "name": "Black Rhino",
        "location": "Kenya",
        "clues": [
            "My horns are made of tightly packed keratin, not bone.",
            "I am a browser, eating from thorny bushes rather than grazing on grass.",
            "I am smaller and generally more aggressive than my white counterpart.",
            "I have a pointed, prehensile upper lip perfectly evolved for grasping twigs.",
            "I roam the dry savannas and scrublands of East Africa, prominently in Kenya.",
        ],
        "conservation_info": "Critically Endangered (Population: ~6,000). They face relentless, highly organized poaching rings hunting them strictly to sell their horns on the black market. To help, wildlife reserves deploy armed, highly trained anti-poaching units and preemptively dehorn rhinos to make them worthless to poachers.",
    },
    {
        "species_id": "darwin-fox",
        "name": "Darwin's Fox",
        "location": "Chile",
        "clues": [
            "I am a small, dark-coated canid with rusty reddish markings.",
            "I do not interbreed with any other canines in my region.",
            "I prefer hunting in dense temperate rainforests over open areas.",
            "I was discovered and named by a famous English naturalist in 1834.",
            "I am an endemic species found mostly on Chiloé Island off the coast of Chile.",
        ],
        "conservation_info": "Endangered (Population: < 1,000). They are threatened by fatal diseases like canine distemper spread by free-roaming domestic dogs entering the national parks. To help, organizations run extensive vaccination campaigns for domestic dogs living near the protected forest borders.",
    },
    {
        "species_id": "harpy-eagle",
        "name": "Harpy Eagle",
        "location": "Brazil",
        "clues": [
            "I have a striking, dark double-crested crown of feathers on my head.",
            "I have talons larger and thicker than a grizzly bear's claws.",
            "I am the largest and most powerful raptor in the Americas.",
            "I can pluck monkeys and sloths right out of the forest canopy.",
            "I require vast tracts of unbroken Neotropical rainforest in Brazil to hunt.",
        ],
        "conservation_info": "Near Threatened (Population: Decreasing). They are affected by commercial logging operations that target and destroy the massive, old-growth canopy trees they require for nesting. To help, conservationists are working with loggers to identify and protect specific nesting trees, and establishing large contiguous forest reserves.",
    },
    {
        "species_id": "tuatara",
        "name": "Tuatara",
        "location": "New Zealand",
        "clues": [
            "I can live for over 100 years.",
            "I have a 'third eye' on the top of my head to sense light cycles.",
            "I am a reptile, but I actually prefer cool, damp temperatures.",
            "I am the only surviving member of an ancient order that thrived during the dinosaur age.",
            "I was decimated by rats and now only survive on heavily protected offshore islands of New Zealand.",
        ],
        "conservation_info": "Vulnerable (Population: ~100,000). They are completely vulnerable to invasive mammalian predators, particularly rats, which eat their eggs and young. To help, conservationists are meticulously eradicating rats from offshore islands and restricting all public access to those sanctuaries.",
    },
    {
        "species_id": "leatherback-turtle",
        "name": "Leatherback Turtle",
        "location": "Costa Rica",
        "clues": [
            "I dive deeper into the freezing ocean than any other reptile.",
            "My throat is lined with backward-facing spines to help me swallow slippery prey.",
            "I am the largest species of turtle in the world.",
            "I lack a hard, bony shell, having instead a flexible, rubbery, dark carapace.",
            "I am a pelagic wanderer, but I frequently nest on the protected tropical beaches of Costa Rica.",
        ],
        "conservation_info": "Vulnerable (Population: Decreasing). They frequently mistake floating plastic shopping bags for their primary food source (jellyfish) and choke or starve. To help, there are global initiatives to reduce single-use plastics and protecting vital nesting beaches from coastal development.",
    },
    {
        "species_id": "hyacinth-macaw",
        "name": "Hyacinth Macaw",
        "location": "Brazil",
        "clues": [
            "I have a bright yellow ring of skin around my eyes and lower beak.",
            "My beak is strong enough to easily crack coconuts and macadamia nuts.",
            "My feathers are entirely deep, vibrant blue.",
            "I am the largest flying parrot in the world.",
            "I am native to the massive Pantanal wetlands of South America, primarily in Brazil.",
        ],
        "conservation_info": "Vulnerable (Population: ~4,000). They are heavily exploited by the illegal exotic pet trade, and habitat loss from cattle ranching clearing their nesting trees. To help, conservationists are installing artificial nest boxes in the Pantanal and cracking down on international bird trafficking rings.",
    },
]
