# backend/scripts/species_data.py

MOCK_SPECIES = [
    {
        "species_id": "red-panda",
        "name": "Red Panda",
        "location": "China",
        "clues": [
            "I have a highly specialized diet, but I am technically classified as a carnivore.",
            "I possess an extended wrist bone that functions like a 'false thumb' to help me grip stalks.",
            "My thick, ringed tail helps me balance in trees and acts as a built-in blanket in the cold.",
            "Despite my name, I am not closely related to the famous black-and-white bear that shares my diet.",
            "I have rust-colored fur and spend most of my time in the high-altitude bamboo forests of the Himalayas.",
        ],
        "conservation_info": "Endangered. Population declined by 50% over 20 years due to habitat fragmentation.",
    },
    {
        "species_id": "snow-leopard",
        "name": "Snow Leopard",
        "location": "Mongolia",
        "clues": [
            "My exceptionally large paws act as natural snowshoes.",
            "Unlike many of my close relatives, my vocal cords mean I cannot roar.",
            "I can leap up to 50 feet across ravines.",
            "My smoky-gray coat is covered in dark rosettes for camouflage.",
            "I am known as the 'Ghost of the Mountains'.",
        ],
        "conservation_info": "Vulnerable. Threats include retaliatory killings by herders and climate change.",
    },
    {
        "species_id": "galapagos-penguin",
        "name": "Galapagos Penguin",
        "location": "Ecuador",
        "clues": [
            "I am the second smallest species of my kind.",
            "I nest in caves and crevices made of volcanic rock.",
            "I rely on the cold Cromwell Current to survive.",
            "I do not live in an icy, polar environment.",
            "I am the only species of my kind found north of the equator.",
        ],
        "conservation_info": "Endangered. Highly susceptible to severe El Niño events causing starvation.",
    },
    {
        "species_id": "sumatran-orangutan",
        "name": "Sumatran Orangutan",
        "location": "Indonesia",
        "clues": [
            "I use sticks to extract honey and insects from tree bark.",
            "I am almost exclusively arboreal.",
            "Mature males develop wide, fleshy cheek pads.",
            "My name translates to 'person of the forest'.",
            "I am a great ape with reddish-orange hair.",
        ],
        "conservation_info": "Critically endangered. Driven by illegal logging and palm oil deforestation.",
    },
    {
        "species_id": "axolotl",
        "name": "Axolotl",
        "location": "Mexico",
        "clues": [
            "I exhibit neoteny, meaning I never undergo metamorphosis.",
            "I can regenerate limbs, spinal cords, and even my heart.",
            "I breathe through large, feathery external gills.",
            "My wild population is nearly extinct due to heavy urbanization.",
            "I am natively found only in the lake complex of Xochimilco.",
        ],
        "conservation_info": "Critically endangered. Threatened by severe water pollution and invasive predatory fish.",
    },
    {
        "species_id": "amur-leopard",
        "name": "Amur Leopard",
        "location": "Russia",
        "clues": [
            "I am adapted to a cool climate, unlike most of my relatives in Africa.",
            "My coat changes from reddish-yellow in summer to light fur in winter.",
            "I am a solitary nocturnal predator.",
            "I can run at speeds up to 37 miles per hour.",
            "There are fewer than 100 of us left in the wild in the Russian Far East.",
        ],
        "conservation_info": "Critically endangered. Primary threats are poaching for fur and habitat loss.",
    },
    {
        "species_id": "vaquita",
        "name": "Vaquita",
        "location": "Mexico",
        "clues": [
            "I am the world's smallest marine mammal.",
            "I have dark rings around my eyes and dark patches on my lips.",
            "I am extremely shy and avoid boats.",
            "I am frequently caught as bycatch in illegal gillnets.",
            "I am found exclusively in the northern Gulf of California.",
        ],
        "conservation_info": "Critically endangered. Fewer than 20 individuals remain due to illegal gillnet fishing.",
    },
    {
        "species_id": "javan-rhino",
        "name": "Javan Rhino",
        "location": "Indonesia",
        "clues": [
            "I have a dusky grey skin that looks like armor plating.",
            "Unlike my African cousins, I only have a single horn.",
            "I am largely solitary and rarely seen.",
            "My entire population is restricted to a single national park.",
            "I am the rarest of the five rhino species.",
        ],
        "conservation_info": "Critically endangered. Around 75 individuals remain in Ujung Kulon National Park.",
    },
    {
        "species_id": "mountain-gorilla",
        "name": "Mountain Gorilla",
        "location": "Rwanda",
        "clues": [
            "I have thicker and longer hair than other apes to survive cold temperatures.",
            "I live in complex social groups led by a dominant silverback.",
            "I am an herbivore, eating mostly leaves, shoots, and stems.",
            "I build a new nest on the ground every night to sleep.",
            "I am found high in the volcanic slopes of the Virunga Massif.",
        ],
        "conservation_info": "Endangered. Threatened by poaching, disease, and habitat loss, though numbers are rising.",
    },
    {
        "species_id": "hawksbill-turtle",
        "name": "Hawksbill Turtle",
        "location": "Australia",
        "clues": [
            "I am named for my narrow, pointed beak.",
            "My diet consists almost exclusively of toxic sea sponges.",
            "My colorful, overlapping carapace scales make me a target.",
            "I am vital to maintaining the health of coral reef ecosystems.",
            "I am a highly migratory marine reptile.",
        ],
        "conservation_info": "Critically endangered. Hunted extensively for their beautiful 'tortoiseshell'.",
    },
    {
        "species_id": "saola",
        "name": "Saola",
        "location": "Vietnam",
        "clues": [
            "I was only discovered by scientists in 1992.",
            "I possess striking white markings on my face.",
            "I have two long, straight, parallel horns.",
            "I am known as the 'Asian Unicorn'.",
            "I am found only in the Annamite Mountains.",
        ],
        "conservation_info": "Critically endangered. Extremely rare, threatened by hunting and snare traps.",
    },
    {
        "species_id": "kakapo",
        "name": "Kakapo",
        "location": "New Zealand",
        "clues": [
            "I am nocturnal and completely flightless.",
            "I freeze like a statue when threatened.",
            "I am the heaviest parrot in the world.",
            "I have a distinct, sweet, musty odor.",
            "I breed only when native Rimu trees fruit heavily.",
        ],
        "conservation_info": "Critically endangered. Decimated by introduced predators like stoats and cats.",
    },
    {
        "species_id": "california-condor",
        "name": "California Condor",
        "location": "United States",
        "clues": [
            "I have a wingspan of nearly 10 feet.",
            "My bald head can flush pink or red depending on my mood.",
            "I am a scavenger that feeds exclusively on carrion.",
            "In 1987, my entire wild population was captured to save us from extinction.",
            "I am the largest land bird in North America.",
        ],
        "conservation_info": "Critically endangered. Lead poisoning from spent ammunition is the main threat.",
    },
    {
        "species_id": "iberian-lynx",
        "name": "Iberian Lynx",
        "location": "Spain",
        "clues": [
            "I have characteristic tufted ears and a short, bobbed tail.",
            "I have a distinct 'beard' of hair around my face.",
            "My diet is almost 90% European rabbits.",
            "A disease wiping out my prey nearly caused my extinction.",
            "I am found only in the Mediterranean forests of the Iberian Peninsula.",
        ],
        "conservation_info": "Endangered. Heavily dependent on rabbit populations which crashed due to disease.",
    },
    {
        "species_id": "tasmanian-devil",
        "name": "Tasmanian Devil",
        "location": "Australia",
        "clues": [
            "I store fat in my tail, so a plump tail means I am healthy.",
            "I have one of the strongest bites per unit body mass of any land predator.",
            "I emit loud, disturbing screeches when competing for food.",
            "I am the world's largest surviving carnivorous marsupial.",
            "A contagious facial tumor disease has decimated my population.",
        ],
        "conservation_info": "Endangered. Devil Facial Tumor Disease (DFTD) has caused massive population crashes.",
    },
    {
        "species_id": "philippine-eagle",
        "name": "Philippine Eagle",
        "location": "Philippines",
        "clues": [
            "I have a shaggy crest of feathers that resembles a lion's mane.",
            "I am one of the largest and most powerful birds of prey.",
            "I am apex predator that sometimes hunts macaques.",
            "I am the national bird of my island country.",
            "I am found only in the mature forests of four islands.",
        ],
        "conservation_info": "Critically endangered. Deforestation and shooting are the primary threats.",
    },
    {
        "species_id": "giant-otter",
        "name": "Giant Otter",
        "location": "Brazil",
        "clues": [
            "I can grow up to 6 feet long.",
            "I have a distinct, pale throat patch unique to each individual.",
            "I am highly social and live in noisy family groups.",
            "I am known locally as the 'river wolf'.",
            "I thrive in the slow-moving rivers of the Amazon and Pantanal.",
        ],
        "conservation_info": "Endangered. Hunted for pelts in the past; currently threatened by habitat degradation.",
    },
    {
        "species_id": "bluefin-tuna",
        "name": "Bluefin Tuna",
        "location": "Japan",
        "clues": [
            "I am warm-blooded, allowing me to dive into freezing depths.",
            "I am built for speed, shaped like a torpedo.",
            "I can weigh over 1,000 pounds.",
            "I cross entire oceans during my migrations.",
            "I am highly prized in the global sushi market.",
        ],
        "conservation_info": "Endangered. Heavily overfished due to massive commercial demand.",
    },
    {
        "species_id": "african-wild-dog",
        "name": "African Wild Dog",
        "location": "Botswana",
        "clues": [
            "I have large, rounded, Mickey Mouse-like ears.",
            "I have a mottled, 'painted' coat pattern unique to me.",
            "My pack has an incredibly high hunting success rate.",
            "We vote on whether to hunt by sneezing.",
            "I roam the vast savannas and plains of sub-Saharan Africa.",
        ],
        "conservation_info": "Endangered. Habitat fragmentation and diseases from domestic dogs are major threats.",
    },
    {
        "species_id": "red-wolf",
        "name": "Red Wolf",
        "location": "United States",
        "clues": [
            "I am smaller than a gray wolf but larger than a coyote.",
            "I have a reddish tinge on my head, ears, and legs.",
            "I was declared extinct in the wild in 1980 before being reintroduced.",
            "I often mate for life and live in tight-knit family packs.",
            "My only wild population is in a peninsula in North Carolina.",
        ],
        "conservation_info": "Critically endangered. Hybridization with coyotes and vehicle strikes are main threats.",
    },
    {
        "species_id": "okapi",
        "name": "Okapi",
        "location": "Democratic Republic of the Congo",
        "clues": [
            "I have zebra-like stripes on my legs and hindquarters.",
            "My tongue is so long I can wash my own eyelids.",
            "I secrete a velvety, waterproofing oil from my dark coat.",
            "Despite my appearance, my closest living relative is the giraffe.",
            "I live exclusively in the dense Ituri rainforest.",
        ],
        "conservation_info": "Endangered. Threatened by logging, illegal mining, and poaching.",
    },
    {
        "species_id": "numbat",
        "name": "Numbat",
        "location": "Australia",
        "clues": [
            "I am a small marsupial, but I do not have a pouch.",
            "I have striking white stripes across my reddish-brown back.",
            "My diet consists entirely of termites.",
            "I use my long, sticky tongue to extract my food.",
            "I am active only during the day, unlike most marsupials.",
        ],
        "conservation_info": "Endangered. Introduced predators like foxes and feral cats devastated populations.",
    },
    {
        "species_id": "aye-aye",
        "name": "Aye-Aye",
        "location": "Madagascar",
        "clues": [
            "I have rodent-like teeth that never stop growing.",
            "I use echolocation to find grubs inside tree bark.",
            "I tap on trees with a highly specialized, elongated middle finger.",
            "Many locals consider me a bad omen.",
            "I am the world's largest nocturnal primate.",
        ],
        "conservation_info": "Endangered. Killed on sight due to local superstitions and habitat loss.",
    },
    {
        "species_id": "golden-lion-tamarin",
        "name": "Golden Lion Tamarin",
        "location": "Brazil",
        "clues": [
            "I am a tiny monkey weighing less than two pounds.",
            "I get my name from the impressive mane of hair around my face.",
            "My bright orange coat makes me highly visible.",
            "I live in small family groups that sleep in tree cavities.",
            "I am found only in the fragmented Atlantic coastal forests.",
        ],
        "conservation_info": "Endangered. Urban expansion heavily fragmented their coastal forest habitat.",
    },
    {
        "species_id": "quokka",
        "name": "Quokka",
        "location": "Australia",
        "clues": [
            "I am a small macropod, related to kangaroos.",
            "I am famous for my seemingly permanent 'smile'.",
            "I have no natural fear of humans.",
            "I can survive for long periods without drinking water.",
            "My largest population is restricted to Rottnest Island.",
        ],
        "conservation_info": "Vulnerable. Mainland populations destroyed by invasive foxes and cats.",
    },
    {
        "species_id": "shoebill",
        "name": "Shoebill",
        "location": "Uganda",
        "clues": [
            "I am a massive, prehistoric-looking bird.",
            "My beak is huge, bulbous, and resembles a wooden clog.",
            "I can stand completely motionless for hours while hunting.",
            "My favorite prey includes lungfish and baby crocodiles.",
            "I inhabit large freshwater swamps in East Africa.",
        ],
        "conservation_info": "Vulnerable. Swamp drainage for agriculture and pollution threaten them.",
    },
    {
        "species_id": "komodo-dragon",
        "name": "Komodo Dragon",
        "location": "Indonesia",
        "clues": [
            "I am the heaviest lizard on Earth.",
            "I have venom glands that induce shock in my prey.",
            "I use my forked tongue to taste the air for carrion.",
            "I am capable of reproducing through parthenogenesis (without a mate).",
            "I am an apex predator isolated to a few lesser Sunda islands.",
        ],
        "conservation_info": "Endangered. Climate change and rising sea levels threaten their island habitats.",
    },
    {
        "species_id": "marine-iguana",
        "name": "Marine Iguana",
        "location": "Ecuador",
        "clues": [
            "I am the only lizard in the world that forages in the ocean.",
            "I sneeze out excess salt from special glands in my nose.",
            "I have a dark body that absorbs sunlight to warm me up after diving.",
            "My blunt snout allows me to scrape algae off underwater rocks.",
            "I am endemic to the Galapagos archipelago.",
        ],
        "conservation_info": "Vulnerable. El Niño events reduce their algae food source drastically.",
    },
    {
        "species_id": "hellbender",
        "name": "Hellbender",
        "location": "United States",
        "clues": [
            "I am the largest aquatic salamander in North America.",
            "I have loose, wrinkly skin that helps me absorb oxygen from the water.",
            "I require cold, fast-moving, highly oxygenated streams.",
            "I am affectionately called the 'snot otter'.",
            "I hide under large, flat rocks in Appalachian rivers.",
        ],
        "conservation_info": "Endangered (in many states). Water pollution and sedimentation destroy their rocky habitats.",
    },
    {
        "species_id": "sun-bear",
        "name": "Sun Bear",
        "location": "Malaysia",
        "clues": [
            "I am the smallest bear species in the world.",
            "I have an exceptionally long tongue used for extracting honey.",
            "I have a distinct U-shaped golden patch on my chest.",
            "I am highly arboreal and sleep in trees.",
            "I inhabit the dense tropical rainforests of Southeast Asia.",
        ],
        "conservation_info": "Vulnerable. Deforestation and the illegal bear bile trade are severe threats.",
    },
    {
        "species_id": "maned-wolf",
        "name": "Maned Wolf",
        "location": "Brazil",
        "clues": [
            "I look like a fox on stilts.",
            "My incredibly long legs help me see above tall grasses.",
            "My urine has a strong odor resembling marijuana.",
            "I am an omnivore, eating mostly lobeira fruit and small rodents.",
            "I roam the Cerrado savannas of South America.",
        ],
        "conservation_info": "Near Threatened/Endangered locally. Habitat conversion to farmland is reducing populations.",
    },
    {
        "species_id": "pygmy-hippo",
        "name": "Pygmy Hippo",
        "location": "Liberia",
        "clues": [
            "I am much smaller and less aquatic than my famous cousin.",
            "I secrete a pink fluid that acts as sunscreen and an antibiotic.",
            "I am nocturnal and solitary.",
            "I seek refuge in forest streams and swamps.",
            "I am endemic to the dense forests of West Africa.",
        ],
        "conservation_info": "Endangered. Logging and hunting for bushmeat restrict them to isolated forest fragments.",
    },
    {
        "species_id": "dugong",
        "name": "Dugong",
        "location": "Australia",
        "clues": [
            "I am a marine mammal related to elephants.",
            "Unlike manatees, I have a fluked tail similar to a dolphin's.",
            "My diet consists almost entirely of seagrass.",
            "My heavy bones act as ballast to keep me grazing on the sea floor.",
            "I inspired ancient sailor tales of mermaids.",
        ],
        "conservation_info": "Vulnerable. Coastal development and water pollution destroy their seagrass beds.",
    },
    {
        "species_id": "narwhal",
        "name": "Narwhal",
        "location": "Canada",
        "clues": [
            "I lack a dorsal fin, allowing me to swim easily under ice.",
            "I can dive up to a mile deep to hunt for halibut.",
            "I communicate using a complex series of clicks and whistles.",
            "Males of my species possess a spiraled tusk that is actually a massive canine tooth.",
            "I am uniquely adapted to the Arctic Ocean.",
        ],
        "conservation_info": "Near Threatened. Highly susceptible to climate change melting Arctic ice and increased shipping traffic.",
    },
    {
        "species_id": "fossa",
        "name": "Fossa",
        "location": "Madagascar",
        "clues": [
            "I look like a mix between a cat, a dog, and a mongoose.",
            "I am the largest mammalian carnivore on my island.",
            "My semi-retractable claws and long tail make me an expert climber.",
            "My favorite prey are lemurs.",
            "I rule the forests of my isolated island nation.",
        ],
        "conservation_info": "Vulnerable. Rampant deforestation on the island has severely fragmented populations.",
    },
    {
        "species_id": "binturong",
        "name": "Binturong",
        "location": "India",
        "clues": [
            "I am often called a 'bearcat', though I am neither.",
            "My scent glands produce a smell exactly like hot buttered popcorn.",
            "I am one of only two carnivores with a fully prehensile tail.",
            "I am a keystone species because I spread fig seeds.",
            "I live in the high canopy of South and Southeast Asian forests.",
        ],
        "conservation_info": "Vulnerable. Threatened by the pet trade, bushmeat hunting, and deforestation.",
    },
    {
        "species_id": "sloth-bear",
        "name": "Sloth Bear",
        "location": "India",
        "clues": [
            "I lack upper incisors, creating a gap that helps me suck up insects.",
            "I have shaggy fur and a prominent white Y-shaped chest mark.",
            "I carry my cubs on my back.",
            "I use my long lower lip like a vacuum to eat termites.",
            "I inhabit the dry and moist forests of the Indian subcontinent.",
        ],
        "conservation_info": "Vulnerable. Habitat loss and human-wildlife conflict are the main pressures.",
    },
    {
        "species_id": "tapir",
        "name": "Tapir",
        "location": "Brazil",
        "clues": [
            "I have a short, prehensile snout used to grab leaves.",
            "My calves are born with watermelon-like stripes and spots for camouflage.",
            "I am an excellent swimmer and use water to escape predators.",
            "I am considered a living fossil, largely unchanged for millions of years.",
            "I am a large, pig-like herbivore found in Neotropical forests.",
        ],
        "conservation_info": "Vulnerable/Endangered. Highly vulnerable to deforestation and hunting due to slow reproduction rates.",
    },
    {
        "species_id": "gharial",
        "name": "Gharial",
        "location": "India",
        "clues": [
            "I am a crocodilian with an exceptionally long, thin snout.",
            "My snout is perfectly adapted for catching fish, my only food.",
            "Adult males grow a bulbous growth on the tip of their snout.",
            "My legs are too weak to lift my belly off the ground.",
            "I live only in clear, fast-flowing freshwater rivers in the subcontinent.",
        ],
        "conservation_info": "Critically endangered. River damming, sand mining, and fishing nets have destroyed their habitats.",
    },
    {
        "species_id": "pangolin",
        "name": "Pangolin",
        "location": "China",
        "clues": [
            "I am the only mammal in the world completely covered in keratin scales.",
            "I roll into a tight, impenetrable ball when threatened.",
            "I lack teeth, using a sticky tongue longer than my body to eat ants.",
            "I walk on my hind legs, using my tail for balance.",
            "I am the most illegally trafficked mammal in the world.",
        ],
        "conservation_info": "Critically endangered. Heavily poached for their scales (used in traditional medicine) and meat.",
    },
    {
        "species_id": "blue-whale",
        "name": "Blue Whale",
        "location": "Antarctica",
        "clues": [
            "My tongue alone weighs as much as an elephant.",
            "I feed almost exclusively on tiny shrimp-like krill.",
            "I am the loudest animal on the planet.",
            "I filter food through baleen plates instead of teeth.",
            "I am the largest animal known to have ever existed on Earth.",
        ],
        "conservation_info": "Endangered. Slow recovery from commercial whaling; currently threatened by ship strikes.",
    },
    {
        "species_id": "asian-elephant",
        "name": "Asian Elephant",
        "location": "India",
        "clues": [
            "I have smaller, more rounded ears than my African counterpart.",
            "Only the males of my species grow visible tusks.",
            "I have a single 'finger' at the end of my trunk.",
            "I maintain matriarchal social herds.",
            "I hold immense cultural significance in Southeast Asian traditions.",
        ],
        "conservation_info": "Endangered. Extreme habitat loss leads to severe human-elephant conflict over crops.",
    },
    {
        "species_id": "green-turtle",
        "name": "Green Turtle",
        "location": "Australia",
        "clues": [
            "I am named not for the color of my shell, but for the color of my fat.",
            "I am unique among my relatives because adults are strict herbivores.",
            "I migrate thousands of miles to nest on the exact beach where I was born.",
            "I rely heavily on seagrass beds for food.",
            "I am a large, hard-shelled marine reptile.",
        ],
        "conservation_info": "Endangered. Threatened by plastic pollution, poaching of eggs, and fishing gear entanglement.",
    },
    {
        "species_id": "whooping-crane",
        "name": "Whooping Crane",
        "location": "United States",
        "clues": [
            "I am the tallest bird in North America.",
            "I have snow-white plumage with a crimson crown.",
            "My distinct, loud call can be heard for miles.",
            "In 1941, my population dropped to just 15 individuals.",
            "I undertake a massive migration from Canada to Texas every year.",
        ],
        "conservation_info": "Endangered. Intense conservation and captive breeding saved them from the brink of extinction.",
    },
    {
        "species_id": "black-rhino",
        "name": "Black Rhino",
        "location": "Kenya",
        "clues": [
            "I have a pointed, prehensile upper lip for grasping twigs and leaves.",
            "I am smaller and more aggressive than my white counterpart.",
            "I am a browser, eating from bushes rather than grazing on grass.",
            "My horns are made of tightly packed keratin.",
            "I roam the dry savannas and scrublands of East and Southern Africa.",
        ],
        "conservation_info": "Critically endangered. Relentless poaching for their horns drives their decline.",
    },
    {
        "species_id": "darwin-fox",
        "name": "Darwin's Fox",
        "location": "Chile",
        "clues": [
            "I am a small, dark-coated canid with rusty markings.",
            "I was discovered by a famous naturalist in 1834.",
            "I do not interbreed with other foxes in my region.",
            "I prefer dense temperate rainforests over open areas.",
            "I am found mostly on Chiloé Island.",
        ],
        "conservation_info": "Endangered. Domestic dogs spread fatal diseases and attack them.",
    },
    {
        "species_id": "harpy-eagle",
        "name": "Harpy Eagle",
        "location": "Brazil",
        "clues": [
            "I have talons larger than a grizzly bear's claws.",
            "I am the largest and most powerful raptor in the Americas.",
            "I pluck monkeys and sloths right out of the canopy.",
            "I have a striking double-crested crown of feathers.",
            "I require vast tracts of unbroken Neotropical rainforest to hunt.",
        ],
        "conservation_info": "Near Threatened/Endangered. Logging destroys the massive trees they need for nesting.",
    },
    {
        "species_id": "tuatara",
        "name": "Tuatara",
        "location": "New Zealand",
        "clues": [
            "I have a 'third eye' on the top of my head to sense light.",
            "I am the only surviving member of an order that thrived during the dinosaur age.",
            "I have two rows of teeth in my upper jaw that overlap one row on the bottom.",
            "I can live for over 100 years.",
            "I am a reptile, but I prefer cool temperatures.",
        ],
        "conservation_info": "Vulnerable. Decimated on the mainland by invasive rats; restricted to offshore islands.",
    },
    {
        "species_id": "leatherback-turtle",
        "name": "Leatherback Turtle",
        "location": "Costa Rica",
        "clues": [
            "I lack a hard, bony shell, having instead a flexible, rubbery carapace.",
            "I am the largest species of turtle in the world.",
            "My throat is lined with backward-facing spines to help me swallow jellyfish.",
            "I dive deeper than any other reptile.",
            "I am a highly pelagic marine wanderer.",
        ],
        "conservation_info": "Vulnerable. They frequently mistake plastic bags for jellyfish and choke.",
    },
    {
        "species_id": "macaw",
        "name": "Hyacinth Macaw",
        "location": "Brazil",
        "clues": [
            "I am the largest flying parrot in the world.",
            "My feathers are entirely deep, vibrant blue.",
            "I have a bright yellow ring around my eyes and lower beak.",
            "My beak is strong enough to crack coconuts and macadamia nuts.",
            "I am native to the Pantanal wetlands of South America.",
        ],
        "conservation_info": "Vulnerable. Heavily exploited by the illegal pet trade and habitat loss.",
    },
]
